## Numpy 기초

- 넘파이 패키지 로드

```python
import numpy as np
```

In [4]:
import numpy as np

### Python 리스트(배열) 과 NumPy 배열 비교

- 파이썬에 기존 리스트(배열) 자료구조 존재. 속도적면에서 NumPy가 우세

#### 파이썬으로 배열작업

In [6]:
prices = [10000, 15000, 12000, 30000, 25000] # 5개 가격이 든 배열

discount_prices =[]

for price in prices:
    discount_prices.append(price * 0.9) # 10% 할인

discount_prices # 노트북 코드쉘에서 하나만 출력하면 print() 생략 가능

[9000.0, 13500.0, 10800.0, 27000.0, 22500.0]

#### NumPy로 배열 작업

In [9]:
np_prices = np.array(prices) # 넘파이 배열로 변경
np_discount_prices = np_prices * 0.9

np_discount_prices.tolist()

[9000.0, 13500.0, 10800.0, 27000.0, 22500.0]

- NumPy 배열은 반복문을 사용하지 않아도 배열전체에 계산을 수행할 수 있음. `벡터화 연산`

#### NumPy 배열 생성

In [10]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [11]:
# 2차원 배열
sales = np.array([
    [100,120,130,],
    [90,110,150],
    [80,140,160]
])

sales

array([[100, 120, 130],
       [ 90, 110, 150],
       [ 80, 140, 160]])

In [14]:
# 파이썬 2차원 배열
tests = [
    [100,120,130,],
    [90,110,150],
    [80,140,160]
]

tests
np.array(tests)

array([[100, 120, 130],
       [ 90, 110, 150],
       [ 80, 140, 160]])

#### 배열 기본 속성

- `ndim` : 배열의 차원수
- `shape` : 배열 행과 열의 구조
- `size` : 전체 데이터 수
- `dtype` : 배열에 저장된 데이터타입

In [16]:
# ndim
print(np_prices.ndim, sales.ndim)

1 2


In [17]:
# shape 행과 열의 구조
np_prices.shape

(5,)

In [18]:
sales.shape

(3, 3)

In [20]:
# size
np_prices.size

5

In [21]:
sales.size

9

In [22]:
np_prices.dtype

dtype('int64')

In [23]:
sales.dtype

dtype('int64')

#### NumPy 데이터타입

- int8 : -128 ~ 127 (총 256)
- int16 : -32768 ~ 32767 (총 65536)
- int 32 : 32비트 정수
- int 64 : 64비트 정수 (NumPy 기본 정수)
- uint8 : 0 ~ 255 / 음수 없는 정수
- uint16 : 0 ~ 65536
- float16 : 실수
- float32 : 32비트 실수
- flaot64 : 64비트 실수(NumPy 기본 실수)
- complex64 : 복소수
- complex128 : 128비트 복소수
- bool : True/False
- str_ : 문자열
- object_ : 객체

### 배열 생성 함수

- 0이나 1로 채워진 기본 배열 생성 함수

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# 파이썬 range() 와 동일
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# 균등배열(표준편차 등)
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### 배열 연산

In [39]:
data = np.array([10, 20, 30, 40, 50])

In [41]:
# 사칙연산
data + 10

array([20, 30, 40, 50, 60])

In [42]:
data - 10

array([ 0, 10, 20, 30, 40])

In [43]:
data * 2

array([ 20,  40,  60,  80, 100])

In [44]:
data / 2

array([ 5., 10., 15., 20., 25.])

In [46]:
# 배열끼리 연산
quantity = np.array([2, 1, 3, 5, 4])
unit_price = np.array([10000, 15000, 12000, 8000, 20000])

sales_prices = unit_price * quantity

sales_prices

array([20000, 15000, 36000, 40000, 80000])

#### 기본 통계함수

- 평균, 최대/최소값, 중앙값, 표준편차 등

In [47]:
scores = np.array([80, 95, 70, 60, 100, 88])

In [48]:
np.sum(scores)

np.int64(493)

In [50]:
np.mean(scores)

np.float64(82.16666666666667)

In [52]:
np.max(scores)

np.int64(100)

In [53]:
np.min(scores)

np.int64(60)

In [55]:
np.median(scores)

np.float64(84.0)

In [56]:
np.std(scores)

np.float64(13.909429255804216)

#### 인덱싱 / 슬라이싱

- 파이썬 배열에서 기능과 유사

In [57]:
data

array([10, 20, 30, 40, 50])

In [ ]:
# 인덱싱
data[1]

np.int64(20)

In [60]:
data[4]

np.int64(50)

In [61]:
data[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [62]:
data[-1]

np.int64(50)

In [63]:
# 슬라이싱
data[:] # 배열전체

array([10, 20, 30, 40, 50])

In [65]:
data[1:4] # 뒤의 수는 n-1까지 인덱스를 추출

array([20, 30, 40])

In [66]:
data[:3]

array([10, 20, 30])

In [67]:
data[4:]

array([50])

In [68]:
# 2차원 배열
sales

array([[100, 120, 130],
       [ 90, 110, 150],
       [ 80, 140, 160]])

In [70]:
sales[0,0] # 0번행 0번열 값 인덱싱

np.int64(100)

In [73]:
sales[1, :] # 1번행의 모든열을 슬라이싱

array([ 90, 110, 150])

In [74]:
sales[:, 2] # 모든행의 2번열 값들을 슬라이싱

array([130, 150, 160])

#### 조건 필터링
- SQL WHERE 절과 동일, 조건에 맞는 데이터만 골라내기

In [78]:
np_prices

array([10000, 15000, 12000, 30000, 25000])

In [81]:
np_prices >= 20000

array([False, False, False,  True,  True])

In [83]:
condition = np_prices >= 20000
condition

array([False, False, False,  True,  True])

In [84]:
np_prices[condition]

array([30000, 25000])

In [85]:
np_prices[np_prices >= 20000]

array([30000, 25000])

In [88]:
datas = np.array([10, -2, 80, 999, 30, 120])
datas

array([ 10,  -2,  80, 999,  30, 120])

In [89]:
datas[(datas >= 0) & (datas <= 100)]

array([10, 80, 30])

#### 결측값 핸들림

- 실제 데이터에서 값이 비어있는 경우, 이를 결측치/결측값이라고 함
- 일반적으로 `NULL`, 파이썬에서는 `None`, NumPy에서는 `np.nan` 로 표현